name = "cf-ai-study-assistant"
main = "src/index.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "SESSION_MANAGER"
class_name = "SessionManager"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionManager"]

[[kv_namespaces]]
binding = "MEMORY_STORE"
id = "18e8ade7781045f99cb6c5cbad0f9d23"

[dev]
port = 8787
local_protocol = "http"